worker_processes  1;

events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;
	client_max_body_size 10M;
	# 演示环境配置
    server {
		listen 80;
		ssl_protocols       TLSv1.2 TLSv1.3;
		ssl_ciphers         HIGH:!aNULL:!MD5;
		ssl_prefer_server_ciphers on;

		# 前端dist
        location / {
            root   /usr/share/nginx/html/dist;
            index  index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        # 将以/prod-api/开头的请求反向代理到8080端口的后端服务
        location /prod-api/ {
            proxy_pass http://lihua-gateway-server:8080/; # 注意这里的尾部斜线
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            # 添加以下配置以处理SSE
            # 避免超时
            proxy_connect_timeout 600s;   # 与后端服务器的连接超时时间
            proxy_send_timeout 600s;      # 发送给后端的超时时间
            proxy_read_timeout 600s;      # 从后端读取响应的超时时间
            proxy_buffering off;
            proxy_cache off;
            proxy_set_header Connection keep-alive;
        }

        # websocket
        location /ws-connect {
    		proxy_pass http://lihua-gateway-server:8080;
    		proxy_http_version 1.1;
    		proxy_set_header Upgrade $http_upgrade;
    		proxy_set_header Connection "upgrade";

    		proxy_set_header Host $host;
   		 	proxy_set_header X-Real-IP $remote_addr;
    		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    		proxy_set_header X-Forwarded-Proto $scheme;

    		proxy_read_timeout 86400;
    		proxy_buffering off;
		}

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }


    }
}
