server:
  port: ${SERVER_PORT}

spring:
  cloud:
    nacos:
      username: ${NACOS_USERNAME}
      password: ${NACOS_PASSWORD}
      # 服务发现
      discovery:
        server-addr: ${NACOS_ADDR}
      # 配置中心
      config:
        namespace: ${spring.profiles.active}
        file-extension: yaml
        import-check:
          enabled: true
  config:
    import:
      - nacos:${spring.application.name}.yaml?group=${spring.application.name}
      - nacos:lihua-common.yaml?group=lihua-common