name: lihua

services:

  # 认证中心
  auth-server:
    container_name: lihua-auth-server
    build:
      context: ./lihua-auth
      dockerfile: dockerfile
    environment:
      - SERVER_PORT=8081
      - NACOS_USERNAME=nacos
      - NACOS_PASSWORD=nacos
      - NACOS_ADDR=lihua-nacos:8848
      - NACOS_NAMESPACE=prod
      - TZ=Asia/Shanghai
    networks:
      - network
    volumes:
      - auth-server-data:/lihua-auth/data/
      - auth-jar-resource:/app/

  # 核心服务
  system-server:
    container_name: lihua-system-server
    build:
      context: ./lihua-system
      dockerfile: dockerfile
    environment:
      - SERVER_PORT=8082
      - NACOS_USERNAME=nacos
      - NACOS_PASSWORD=nacos
      - NACOS_ADDR=lihua-nacos:8848
      - NACOS_NAMESPACE=prod
      - TZ=Asia/Shanghai
    networks:
      - network
    volumes:
      - system-server-data:/lihua-system/data/
      - system-jar-resource:/app/

  # 文件服务
  file-server:
    container_name: lihua-file-server
    build:
      context: ./lihua-file
      dockerfile: dockerfile
    environment:
      - SERVER_PORT=8083
      - NACOS_USERNAME=nacos
      - NACOS_PASSWORD=nacos
      - NACOS_ADDR=lihua-nacos:8848
      - NACOS_NAMESPACE=prod
      - TZ=Asia/Shanghai
    networks:
      - network
    volumes:
      - file-server-data:/lihua-file/data/
      - file-jar-resource:/app/

  # 监控服务
  monitor-server:
    container_name: lihua-monitor-server
    build:
      context: ./lihua-monitor
      dockerfile: dockerfile
    environment:
      - SERVER_PORT=8084
      - NACOS_USERNAME=nacos
      - NACOS_PASSWORD=nacos
      - NACOS_ADDR=lihua-nacos:8848
      - NACOS_NAMESPACE=prod
      - TZ=Asia/Shanghai
    networks:
      - network
    volumes:
      - monitor-server-data:/lihua-monitor/data/
      - monitor-jar-resource:/app/

  # 网关服务
  gateway-server:
    container_name: lihua-gateway-server
    build:
      context: ./lihua-gateway
      dockerfile: dockerfile
    environment:
      - SERVER_PORT=8080
      - SPRING_CLOUD_NACOS_SERVER_ADDR=lihua-nacos:8848
      - SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR=lihua-nacos:8848
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR=lihua-nacos:8848
      - NACOS_USERNAME=nacos
      - NACOS_PASSWORD=nacos
      - NACOS_ADDR=lihua-nacos:8848
      - NACOS_NAMESPACE=prod
      - TZ=Asia/Shanghai
    networks:
      - network
    volumes:
      - gateway-server-data:/lihua-gateway/data/
      - gateway-jar-resource:/app/

  # 前端 vue
  client:
    container_name: lihua-web-client
    build:
      context: ./client
      dockerfile: dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - network
    volumes:
      - dist-resource:/usr/share/nginx/html/

  # mysql数据库
  mysql:
    container_name: lihua-mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Shanghai
    networks:
      - network
    volumes:
      - mysql-conf:/etc/mysql/
      - mysql-data:/var/lib/mysql

  # redis 缓存
  redis:
    container_name: lihua-redis
    image: redis:7
    command: redis-server --requirepass password
    networks:
      - network
    volumes:
      - redis-data:/data/
    ports:
      - "6379:6379"

  # nacos 注册配置中心
  nacos:
    container_name: lihua-nacos
    image: nacos/nacos-server:v3.1.1
    environment:
      - MODE=standalone
      - NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_TOKEN=token
      - NACOS_AUTH_IDENTITY_KEY=nacos
      - NACOS_AUTH_IDENTITY_VALUE=nacos
      - JVM_XMS=256m
      - JVM_XMX=512m
      - JVM_XMN=128m
    ports:
      - "8090:8080"
      - "8848:8848"
      - "9848:9848"
    networks:
      - network

# 容器间共享网络
networks:
  network:

# 卷挂载
volumes:
  mysql-conf:
  mysql-data:
  redis-data:
  dist-resource:

  auth-server-data:
  auth-jar-resource:

  system-server-data:
  system-jar-resource:

  file-server-data:
  file-jar-resource:

  gateway-server-data:
  gateway-jar-resource:

  monitor-server-data:
  monitor-jar-resource: