 # 系统配置
token:
  # 令牌过期时间（分钟）
  tokenExpireTime: 1440
  # 令牌刷新阈值（分钟）距令牌过期15分钟内时，有新请求时对令牌进行刷新
  refreshThreshold: 15

# 处理因linux系统临时文件清理导致文件上传报错
server:
  tomcat:
    basedir: ${BASE_FILE_PATH}temp

# 数据源配置
spring:
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://${DB_HOST}:${DB_PORT}/lihua
          username: ${DB_USERNAME}
          password: ${DB_PASSWORD}
          hikari:
            # 最大连接数默认 10
            maximum-pool-size: 20
            # 最小空闲连接 默认10
            minimum-idle: 5
            # 等待连接池连接最大时长（毫秒）
            connection-timeout: 5000
            # 空闲连接最大时长（毫秒）
            idle-timeout: 120000
            # 连接生命时长（毫秒）
            max-lifetime: 1800000
# 多数据源配置，使用dynamic-datasource实现，具体文档请参考：https://www.kancloud.cn/tracy5546/dynamic-datasource/2264611
#        slave_1:
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://localhost:3306/dynamic
#          username: root
#          password: 123456
#          hikari:
#            # 最大连接数默认 10
#            maximum-pool-size: 30
#            # 最小空闲连接 默认10
#            minimum-idle: 30
#            # 等待连接池连接最大时长（毫秒）
#            connection-timeout: 5000
#            # 空闲连接最大时长（毫秒）
#            idle-timeout: 0
#            # 连接生命时长（毫秒）
#            max-lifetime: 25800

  # redisson配置，官方文档：https://redisson.pro/docs/integration-with-spring/#spring-boot-starter
  redis:
    redisson:
      config: |
        singleServerConfig:
          address: "redis://${REDIS_HOST}:${REDIS_PORT}"
          password: ${REDIS_PASSWORD}
          database: 0
          # 命令超时时间
          timeout: 3000
          # 连接超时时间
          connectTimeout: 10000
          # 连接池最大连接数
          connectionPoolSize: 64
          # 最小空闲连接数
          connectionMinimumIdleSize: 10
        # 自定义序列化器
        codec: !<com.lihua.cache.config.TypedRedissonJsonCodec> {}

# 日志配置
logging:
  file:
    name: ${BASE_FILE_PATH}logs/lihua.log
  level:
    com.lihua: debug
    org.springframework: info

# 定时任务
# 如需启用需要从启动类【com/lihua/LiHuaApplication.java】中将 @EnableSnailJob 注释解除
snail-job:
  server:
    host:
    port:
  namespace:
  group:
  token:

 # spring doc 接口文档
springdoc:
  api-docs:
    enabled: false
    path: /v3/api-docs
  swagger-ui:
    enabled: false
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
